Iter9
konstantin-kukharev/metrics pull request #9
Opened 2024-12-24 00:20 UTC by konstantin-kukharev

2024-12-24 11:05 UTC, zhark0vv requested changes

2024-12-24 11:05 UTC, zhark0vv commented on .DS_Store
Загитигнорь этот файл, пожалуйста.

2024-12-24 11:05 UTC, zhark0vv commented on cmd/agent/main.go
> +func run(app *settings.Config, l Logger) error {
Слой main уже использует зависимости, но не определяет их. 
Стоит вынести интерфейсы и метод run за пределы main.

2024-12-24 11:05 UTC, zhark0vv commented on cmd/server/application/reporter.go
> +type Source interface {
Этот интерфейс можно сделать приватным.

2024-12-24 11:05 UTC, zhark0vv commented on cmd/server/application/reporter.go
> +func NewReporter(f *os.File, s Source, i time.Duration) *Reporter {
Тут два предложения по улучшению:

1. Не использовать файл, вместо него использовать `io.Writer` - пусть потребитель решает куда писать, не стоит навязывать ему только файл;
2. Вместо pull-модели (читаем весь репо и кладем в файл) использовать push-модель, класть событие в канал на уровне бизнес-логики, а тут его читать. Это сэкономит ресурсы на накладных расходах.

2024-12-24 11:05 UTC, zhark0vv commented on internal/graceful/graceful.go
> +package graceful
Крутая идея!

2024-12-24 11:05 UTC, zhark0vv commented on internal/const.go
> +const DefaultServerStoreInterval = 300
```
const (
...
)
```

2024-12-24 11:05 UTC, zhark0vv commented on internal/repository/memory/metric.go
> +type Logger interface {
Как мне кажется, логгер можно таскать и по реализации, не абстрагируя его.
Но это опционально.

2024-12-25 23:28 UTC, konstantin-kukharev commented on internal/repository/memory/metric.go
> +type Logger interface {
Поменяю, но пожалуй не в этой итерации, если можно. Мне не нравится реализация с интерфейсами, не хочется таскать логгер через context.Value (придется менять сигнатуру функций по всему проекту). Есть еще отложенные для просмотра лекции на эту тему ребят из Ozon, может там есть что-то интересное. Ну и думаю поменять логгер на zap

2024-12-26 06:03 UTC, zhark0vv commented on internal/repository/memory/metric.go
> +type Logger interface {
Я тут, скорее про то, что можно использовать _*logger.Logger_, вместо интерфейсов.

2024-12-26 08:11 UTC, zhark0vv commented on cmd/server/application/reporter.go
> +func NewReporter(f *os.File, s Source, i time.Duration) *Reporter {
Тут решил не исправлять?

2024-12-26 16:26 UTC, konstantin-kukharev commented on cmd/server/application/reporter.go
> +func NewReporter(f *os.File, s Source, i time.Duration) *Reporter {
поправлено ж https://github.com/konstantin-kukharev/metrics/blob/d2bde09438ffd3ee296ccf85ae754279442fc3fe/cmd/server/application/reporter.go#L21

2024-12-27 08:26 UTC, konstantin-kukharev commented on internal/repository/memory/metric.go
> +type Logger interface {
Если правки опциональные, предлагаю следующий вариант : кроме логов у меня есть желание отрефакторить shutdown(какие-то проблемы с race, которые могут выстрелить на спринте с рутинами) и репозитории. предполагаю сделать это в новогодние праздники, на спринте с БД. Можем договориться о правке логера на следующей итерации?

2024-12-27 17:40 UTC, konstantin-kukharev commented
added logs & file backup

2024-12-27 17:41 UTC, merged